<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="MAIN" Id="{dbec18cf-ca82-4287-a487-95b423752fd7}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	counter1	:	FB_TestFunctionBlock;
	counter2	:	FB_TestFunctionBlock;	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[counter1();
counter2();
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>